# NOTE - Run "sudo -E bash -c 'docker-compose up -d'" to fetch PWD
version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: ./src/main/resources/docker/Dockerfile
    image: payroll
    container_name: payroll-api
    restart: unless-stopped
    networks:
      - api

  db:
    image: postgres
    container_name: "database"
    environment:
      - POSTGRES_DB=payroll
      - POSTGRES_USER=payroll
      - POSTGRES_PASSWORD=payroll
      - TZ=GMT
    volumes:
      - postgres-volume:/var/lib/postgresql/payroll_data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5432" ]
      interval: 35s
      timeout: 20s
      retries: 5
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - api

  flyway:
    image: flyway/flyway
    command: migrate
    environment:
      - FLYWAY_USER=payroll
      - FLYWAY_PASSWORD=payroll
      - FLYWAY_URL=jdbc:postgresql://172.27.0.3:5432/payroll
      - FLYWAY_SCHEMAS=payroll
      - FLYWAY_GROUP=true
    volumes:
#      - ${PWD}/src/main/resources/db:/flyway/conf
      - ${PWD}/src/main/resources/db/migration:/flyway/sql
    depends_on:
      - db
    networks:
      - api

volumes:
  postgres-volume:
    driver: local

networks:
  api:
    driver: bridge
